name: Terraform ECS Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy resources'
        required: false
        default: 'false'

jobs:
  terraform:
    name: 'Terraform ECS Deployment Workflow'
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Step 2: Initialize and Apply Terraform in the s3 folder
    - name: 'Terraform Init in s3 folder'
      run: terraform init
      working-directory: ./s3

    - name: 'Terraform Plan in s3 folder'
      run: terraform plan
      working-directory: ./s3

    - name: 'Terraform Apply in s3 folder'
      run: terraform apply -auto-approve
      working-directory: ./s3

    - name: 'Terraform Destroy in s3 folder'
      if: ${{ github.event.inputs.destroy == 'true' }}
      run: terraform destroy -auto-approve
      working-directory: ./s3

    # Step 3: Configure Backend for s3 and alasco
    - name: 'Re-initialize Terraform in s3 folder with S3 backend'
      run: terraform init -reconfigure
      working-directory: ./s3

    - name: 'Re-initialize Terraform in alasco folder with S3 backend'
      run: terraform init -reconfigure
      working-directory: ./alasco

    # Run Terraform commands in the alasco folder
    - name: 'Terraform Init in alasco folder'
      run: terraform init
      working-directory: ./alasco

    - name: 'Terraform Plan in alasco folder'
      run: terraform plan
      working-directory: ./alasco

    - name: 'Terraform Apply in alasco folder'
      run: terraform apply -auto-approve
      working-directory: ./alasco

    - name: 'Terraform Destroy in alasco folder'
      if: ${{ github.event.inputs.destroy == 'true' }}
      run: terraform destroy -auto-approve
      working-directory: ./alasco
