name: Terraform ECS Deploy

# on:
#   push:
#     paths:
#       - 'terraform.tfvars'
#       - '**/terraform.tfvars'

  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy resources'
        required: false
        default: 'false'

jobs:
  terraform:
    name: 'Terraform ECS Deployment Workflow'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: 'Check if backend initialized in ledgerndary folder'
      id: ledgerndary_backend_check
      run: |
        if [ -f .terraform-initialized ]; then
          echo "Backend already initialized"
          echo "backend_initialized=true" >> $GITHUB_ENV
        else
          echo "backend_initialized=false" >> $GITHUB_ENV
        fi
      working-directory: ./ledgerndary

    - name: 'Terraform Init in ledgerndary folder'
      run: |
        if [ "$backend_initialized" = "false" ]; then
          terraform init -reconfigure
          touch .terraform-initialized
        else
          terraform init
        fi
      working-directory: ./ledgerndary

    - name: 'Terraform Plan in ledgerndary folder'
      run: terraform plan
      working-directory: ./ledgerndary

    - name: 'Terraform Apply in ledgerndary folder'
      run: terraform apply -auto-approve
      working-directory: ./ledgerndary

    - name: 'Terraform Destroy in ledgerndary folder'
      if: ${{ github.event.inputs.destroy == 'true' }}
      run: terraform destroy -auto-approve
      working-directory: ./ledgerndary